### ISSUE TITLE
Valheim - Not working with 0.217.24

### ISSUE THREAD

**Issue by Siggennn** [AzumattDev/BepInEx#7]
After the 0.217.24 release, I cant load into any world, even if i create a new one. I also now randomly have a character named Ragnar which i never created. I have troubleshooted all my mods and can confirm this is the game breaking one.

**Comment by LadyWolfheart** [comment]
EDIT: After several hours of troubleshooting, the issue was due to a specific mod. Once disabled, game launched as expected.

I am having the same issue. The game launches with no character model in the load screen and when I click "Start Game", there's a character named Ragnar (I also never created this) and there's no model.  I am getting two errors:

1. [Error  : Unity Log] MissingMethodException: void Terminal/ConsoleCommand..ctor(string,string,Terminal/ConsoleEvent,bool,bool,bool,bool,bool,Terminal/ConsoleOptionsFetcher,bool)
Stack trace:
(wrapper dynamic-method) Console.DMD<Console::Awake>(Console)
UnityEngine.Object:Instantiate(GameObject)
FejdStartup:DMD<FejdStartup::Awake>(FejdStartup)

and 
 
2. [Error  : Unity Log] MissingFieldException: Field 'FejdStartup.m_connectionFailedError' not found.
Stack trace:
(wrapper dynamic-method) FejdStartup.DMD<FejdStartup::ShowConnectError>(FejdStartup,ZNet/ConnectionStatus)
(wrapper dynamic-method) FejdStartup.DMD<FejdStartup::Start>(FejdStartup)

**Comment by dp63split** [comment]
> EDIT: After several hours of troubleshooting, the issue was due to a specific mod. Once disabled, game launched as expected.
> 
Which mod was it?

**Comment by AzumattDev** [comment]
Missing methods and errors are caused by outdated mods. Make sure you are only using mods for the current game patch.

**Comment by Siggennn** [comment]
I am certain it is bepinex because I've tried running the game ONLY with bepinex enabled and the error is still there. I have also tried reinstalling the game, even deleting the whole folder altogether, without luck. Is there perhaps another link I can try?

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by LadyWolfheart** [comment]
I initially also did a new profile and launched with BepInEx, that worked fine.

The mod that gave me the trouble was AutoMapPins by FixitFelix - don't think that one's been updated yet; when I disabled it, the game launched fine. Per the Discord, there seems to be hit or miss with some working, others not - including running with BepInEx only. There's definitely some weirdness going on after the second patch on 6 Oct.

**Comment by Siggennn** [comment]
Yeah, seems the update broke my modded game. Is there anything that can be done to fix this? As said previously, i can confirm it is only BepInEx causing these troubles as I've ran the game with only this enabled and the issues persist.

**Comment by syntruth** [comment]
I can confirm that here as well. Completely reinstalled the dedicated server, using only BepInEx and no mods and it crashes, complaining about corrupted files on the `_Data` directory.

I've removed and installed _**everything**_. Twice. Restarted the computer. I haven't burned any incense or made any other offerings at this point, however.

I'm launching with, from dedicated server folder, via the (edited) `start_headless_server.bat` file:

```sh
valheim_server -nographics -batchmode -name "Test Server" -port 2456 -public 0 -world "Test World" -password "********" -crossplay --doorstop-enable true --doorstop-target "C:\Users\games\AppData\Roaming\r2modmanPlus-local\Valheim\profiles\Default\BepInEx\core\BepInEx.Preloader.dll"
```

Attached the log file.

[bepinex-plode.txt](https://github.com/AzumattDev/BepInEx/files/12851862/bepinex-plode.txt)

**Comment by AzumattDev** [comment]
> I can confirm that here as well. Completely reinstalled the dedicated server, using only BepInEx and no mods and it crashes, complaining about corrupted files on the `_Data` directory.
> 
> I've removed and installed _**everything**_. Twice. Restarted the computer. I haven't burned any incense or made any other offerings at this point, however.
> 
> I'm launching with, from dedicated server folder, via the (edited) `start_headless_server.bat` file:
> 
> ```shell
> valheim_server -nographics -batchmode -name "Test Server" -port 2456 -public 0 -world "Test World" -password "********" -crossplay --doorstop-enable true --doorstop-target "C:\Users\games\AppData\Roaming\r2modmanPlus-local\Valheim\profiles\Default\BepInEx\core\BepInEx.Preloader.dll"
> ```
> 
> Attached the log file.
> 
> [bepinex-plode.txt](https://github.com/AzumattDev/BepInEx/files/12851862/bepinex-plode.txt)

I tested using this configuration with r2modman like you have. My server was able to boot locally just fine. There aren't any issues with the BepInEx pack for this version. Your installations must be corrupt or not clean like you think they are. For the other people above, I would assume the same thing or they are using outdated mods. 

Here is the content of my `start_headless_server.bat`

```bat
@echo off
set SteamAppId=892970

echo "Starting server PRESS CTRL-C to exit"

REM Tip: Make a local copy of this script to avoid it being overwritten by steam.
REM NOTE: Minimum password length is 5 characters & Password cant be in the server name.
REM NOTE: You need to make sure the ports 2456-2458 is being forwarded to your server through your local router & firewall.
REM valheim_server -nographics -batchmode -name "My server" -port 2456 -world "Dedicated" -password "secret" -crossplay
valheim_server -nographics -batchmode -name "Test Server" -port 2456 -public 0 -world "Test World" -password "********" -crossplay --doorstop-enable true --doorstop-target "C:\Users\crypt\AppData\Roaming\r2modmanPlus-local\Valheim\profiles\ValheimServerTest\BepInEx\core\BepInEx.Preloader.dll" %*
```

**Comment by syntruth** [comment]
For others who come here about the above error, I think I figured it out on our server: McAfee was mucking with the files for some reason.

I followed your suggestion by nuking everything again; Valheim server and r2modman, all folders and files. After reinstalling I tried a bare bones BepInEx modded server AGAIN and recieved the same errors, AGAIN. Since I'm running the server on a new Win11 HP machine, it was still nagging me about updating its free McAfee trial, and it annoyed me enough to uninstall and reboot. Afterwards, my BepInEx server loaded up perfectly, and then my fully modded setup ALSO ran perfectly. It is LITERALLY the only thing I changed, I didn't even touch my server aside from running it again.

So, to any one coming in with the same problem, you might want to check your antivirus and see if it's interfering with anything.

**Comment by Siggennn** [comment]
Thanks for taking your time to troubleshoot. The mod is almost working fine now. The only new problem I have encountered, is that the standard developer console is gone and replaced by the bepinex F5 displaying all sorts of weird messages. None of the normal devcommands are working, and when trying to type the suggested commands, pressing enter does nothing - the menu with the text written is just standing still as if imma write more. Any suggestions to how i can solve this? Vanilla works perfectly fine with F5 and devcommands

**Comment by Siggennn** [comment]
Thank you for taking your time to troubleshoot. Everythings working as it should now :)
